### ISSUE TITLE
Add packagist webhook to GitHub repo

### ISSUE THREAD

**Issue by joeparsons** [az-digital/arizona-bootstrap-packagist#2]
We need to add a webhook for the https://packagist.org/packages/az-digital/arizona-bootstrap packagist repo to this GitHub repo so updates to github branches / tags are automatically added to Packagist.

## Conditions of satisfaction
- [ ] Should have packagist webhook added to GitHub settings for this repository

**Comment by danahertzberg** [comment]
@joeparsons @kevcooper Is this complete?

**Comment by joeparsons** [comment]
Verified this is complete.
