### ISSUE TITLE
Add GitHub Actions workflow for updating dist assets

### ISSUE THREAD

**Issue by joeparsons** [az-digital/arizona-bootstrap-packagist#3]
## Conditions of satisfaction
- [ ] Should provide GitHub actions workflow that can:
  - Clone arizona-bootstrap
  - Build dist assets
  - Update local copy dist assets
  - Commit changes
- [ ] GitHub actions workflow can be triggered by release or tag event on Arizona Bootstrap repo
- [ ] GitHub actions workflow will replicate tag from Arizona Bootstrap repo

**Comment by danahertzberg** [comment]
Created as part of the original plan. No longer needed. Resolved by AZ bootstrap issue #131.
